name: Deploy to EC2 via SSH

on:
  push:
    branches: [main]
env:
  AWS_REGION: 'us-east-1'
  EC2_INSTANCE_ID: 'i-09e2451804968eb07'
  EC2_INSTANCE_IP: '52.201.230.252'
  SSH_USERNAME: 'ubuntu'
  REMOTE_DIR: '/home/ubuntu/app'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan ${{ env.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts
      - name: Copy files via SCP
        run: |
           scp -i ~/.ssh/deploy_key -r ./* ${{ env.SSH_USERNAME }}@${{ env.EC2_INSTANCE_IP }}:${{ env.REMOTE_DIR }}

      - name: Run remote commands via SSH
        run: |
           ssh -i ~/.ssh/deploy_key ${{ env.SSH_USERNAME }}@${{ env.EC2_INSTANCE_IP }} << 'EOF'
           cd ${{ env.REMOTE_DIR }}
           npm install
           pm2 restart all
           EOF
